#!/bin/sh /etc/rc.common

START=99

start() {
    modprobe snd_soc_meson_axg_fifo
    modprobe snd_soc_meson_axg_frddr
    modprobe snd_soc_meson_axg_toddr
    modprobe snd_soc_meson_axg_tdmout
    modprobe snd_soc_meson_axg_tdm_interface
    modprobe snd_soc_meson_axg_tdm_formatter
    modprobe snd_soc_meson_aiu
    modprobe snd_soc_meson_codec_glue
    modprobe snd_soc_meson_g12a_tohdmitx
    modprobe snd_soc_meson_g12a_toacodec
    modprobe snd_soc_meson_axg_sound_card
}
