# ==================== 文件与目录 ====================
music_directory     "/mnt/mmcblk2p4/music"
playlist_directory  "/tmp/mpd/playlists"
db_file             "/tmp/mpd/database"
log_file            "/tmp/mpd/log"
state_file          "/tmp/mpd/state"
sticker_file        "/tmp/mpd/sticker.sql"


user              "root"
group             "root"

# ==================== 网络监听 ====================
bind_to_address "0.0.0.0"
port "6600"

# ==================== 音频输出 (PulseAudio) ====================
audio_output {
    type            "pulse"
    name            "PulseAudio Bluetooth"
    # server          "127.0.0.1" 
    # sink "bluez_sink.BB_F0_24_A6_CD_4C.a2dp_sink"
}

# ==================== 通用选项 ====================
auto_update         "yes"
filesystem_charset  "UTF-8"
metadata_to_use     "Artist,Album,Title,Track,Date,Genre"
log_level           "default"     
# 排错用，稳定后改为 "notice"
restore_paused      "yes"          
# 重启后不自动播放，避免蓝牙未就绪时爆音
save_absolute_paths_in_playlists "no"

# ==================== 输入插件 ====================
input {
    plugin          "curl"
}
