dnsconf:
    - name: ""
      ipv4:
        enable: false
        gettype: url
        url: https://myip.ipip.net, https://ddns.oray.com/checkip, https://ip.3322.net, https://4.ipw.cn, https://v4.yinghualuo.cn/bejson
        netinterface: br-lan
        cmd: ""
        domains:
            - ""
      ipv6:
        enable: true
        gettype: netInterface
        url: https://speed.neu6.edu.cn/getIP.php, https://v6.ident.me, https://6.ipw.cn, https://v6.yinghualuo.cn/bejson
        netinterface: br-lan
        cmd: ""
        ipv6reg: '@1'
        domains:
            - www.vinsonkong2014.eu.org
            - vinsonkong2014.eu.org
      dns:
        name: dnspod
        id: "387558"
        secret: c6df97d0e7058959b33c509238bf593c
      ttl: ""
user:
    username: vinsonkong
    password: $2a$10$LZKvquIdlxOEBKvasXsER.NIEYqeZ5mgMV.8BIp112ctx0siuB89W
webhook:
    webhookurl: ""
    webhookrequestbody: ""
    webhookheaders: ""
notallowwanaccess: false
lang: zh
