instance_name = "vinson"
hostname = "X96max"
ipv4 = "10.0.30.10"

[network_identity]
network_name = "vinsonkong"
network_secret = "14371250kong"

[[peer]]
uri = "tcp://ramon2009.dpdns.org:11010"

[[peer]]
uri = "tcp://39.108.52.138:11010"

[[peer]]
uri = "tcp://et1.fuis.top:11010"
