#!/bin/sh /etc/rc.common
START=19
STOP=90
USE_PROCD=1

start_service() {
    mkdir -p /dev/binderfs
    procd_open_instance
    procd_set_param command /bin/mount -t binder binder /dev/binderfs
    procd_close_instance
}

stop_service() {
    umount /dev/binderfs 2>/dev/null
}
