#!/bin/sh /etc/rc.common

START=95
STOP=01
USE_PROCD=1
PROG=/usr/bin/mpd
CONFIG=/etc/mpd.conf

start_service() {
	procd_open_instance
	procd_set_param command $PROG --no-daemon $CONFIG
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	:
}

reload_service() {
	procd_send_signal mpd HUP
}
