#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10

NAME=navidrome
BIN=/mnt/mmcblk2p4/tools/navidrome/bin/navidrome
CONF=/mnt/mmcblk2p4/tools/navidrome/config/navidrome.toml
USER=root

# 启动服务
start_service() {
    procd_open_instance
    procd_set_param command $BIN --configfile $CONF
    procd_set_param user $USER
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_close_instance
}

# 停止服务
stop_service() {
    killall $NAME
}

restart() {
    stop
    start
}
